#server.port=8081
#
##spring.datasource.url=jdbc:h2:file:./data/complaintdb
##spring.datasource.driverClassName=org.h2.Driver
##spring.datasource.username=sa
##spring.datasource.password=
##
##spring.jpa.hibernate.ddl-auto=update
##spring.jpa.show-sql=true
##
##spring.h2.console.enabled=true
##spring.h2.console.path=/h2-console
#
#
spring.datasource.url=${url}
spring.datasource.username=${username}
spring.datasource.password=${password}
#
## MySQL Driver
##spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA / Hibernate Configuration
##spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update
#
#
#spring.jpa.show-sql=true
#
jwt.secret=ComplaintManagementSecretKey12345678901234567890
jwt.expiration=86400000
#logging.level.org.springframework.security=DEBUG
#
## EMAIL CONFIGURATION
#
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cms.notifications.aditya@gmail.com
spring.mail.password=xpem ubri okli iahj
#
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true


server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true